apiVersion: v1
kind: Service
metadata:
  name: minio-microservice
  namespace: statex-apps
  labels:
    app: minio-microservice
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: minio-microservice
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: http
