const CONFIG = {
  leadsUrl: "https://leads.alfares.cz/api/leads/submit",
  authBase: "https://auth.alfares.cz",
  clientId: "minio-microservice",
  s3Endpoint: "https://minio.alfares.cz",
  adminApiBase: `${window.location.origin}/api/admin`,
  adminRoles: ["global:superadmin", "app:minio-microservice:admin", "internal:minio-microservice:admin"]
};
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
function randomState(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function authUrl(mode,targetPath){const state=randomState();sessionStorage.setItem("minio_auth_state",state);const path=targetPath || (document.body.dataset.page === "admin" ? "/admin/" : "/client/");const returnUrl=`${window.location.origin}${path}`;return `${CONFIG.authBase}/${mode}?return_url=${encodeURIComponent(returnUrl)}&client_id=${encodeURIComponent(CONFIG.clientId)}&state=${encodeURIComponent(state)}`}
function saveTokensFromHash(){if(!window.location.hash.includes("access_token"))return;const params=new URLSearchParams(window.location.hash.slice(1));const expected=sessionStorage.getItem("minio_auth_state");const returned=params.get("state");if(expected&&returned&&expected!==returned){sessionStorage.removeItem("minio_auth_state");return}const token=params.get("access_token");if(token)sessionStorage.setItem("minio_access_token",token);const refresh=params.get("refresh_token");if(refresh)sessionStorage.setItem("minio_refresh_token",refresh);history.replaceState(null,"",window.location.pathname)}
async function validateAuth(){const token=sessionStorage.getItem("minio_access_token")||localStorage.getItem("minio_access_token");if(!token)return null;try{const res=await fetch(`${CONFIG.authBase}/auth/validate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});if(!res.ok)throw new Error(`Auth validation failed: ${res.status}`);return await res.json()}catch(error){console.warn(error);return null}}
function normalizeRoles(authUser){return authUser?.roles||authUser?.user?.roles||authUser?.data?.roles||[]}
function userLabel(authUser){return authUser?.email||authUser?.user?.email||authUser?.data?.email||"authenticated user"}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function renderApplications(){const table=$("[data-app-table]");if(!table)return;const apps=JSON.parse(localStorage.getItem("minio_customer_apps")||"[]");const rows=apps.length?apps:[{appName:"No applications yet",environment:"-",origin:"Submit the form to prepare onboarding",status:"draft"}];table.innerHTML=rows.map(app=>`<tr><td>${escapeHtml(app.appName)}</td><td>${escapeHtml(app.environment)}</td><td>${escapeHtml(app.origin)}</td><td>${escapeHtml(app.status||"draft")}</td></tr>`).join("")}
async function submitLead(event){event.preventDefault();const form=event.currentTarget;const status=$("[data-lead-status]");const data=new FormData(form);const marketingConsent=data.get("marketingConsent")==="on";const payload={sourceService:"minio-microservice",sourceUrl:window.location.href,sourceLabel:"request-access",message:data.get("message"),contactMethods:[{type:"email",value:data.get("email")}],preferredChannel:"email",metadata:{name:data.get("name"),company:data.get("company"),intent:"request_access",surface:"minio_landing",productKey:"minio"},marketingConsent};if(marketingConsent){payload.consentSource="minio-landing-request-access-checkbox";payload.consentCapturedAt=new Date().toISOString()}status.textContent="Submitting lead request...";try{const res=await fetch(CONFIG.leadsUrl,{method:"POST",headers:{"Content-Type":"application/json","X-Service-Name":"minio-microservice-landing"},body:JSON.stringify(payload)});if(!res.ok)throw new Error(`Lead submission failed: ${res.status}`);const response=await res.json();localStorage.setItem("minio_last_lead",JSON.stringify(response));const leadState=$("[data-lead-state]");if(leadState)leadState.textContent=`Submitted: ${response.status||"new"}`;status.textContent="Lead submitted. Continue with Auth registration when ready."}catch(error){status.textContent="Lead submission could not be completed. Try again or contact the operator.";console.warn(error)}}
function addApplication(event){event.preventDefault();const data=new FormData(event.currentTarget);const apps=JSON.parse(localStorage.getItem("minio_customer_apps")||"[]");apps.push({appName:data.get("appName"),environment:data.get("environment"),origin:data.get("origin"),status:"awaiting approval"});localStorage.setItem("minio_customer_apps",JSON.stringify(apps));event.currentTarget.reset();renderApplications()}
async function refreshAdminHealth(){const live=$("[data-health-live]");const ready=$("[data-health-ready]");if(!live||!ready)return;live.textContent="Checking";ready.textContent="Checking";await Promise.all([probe(`${CONFIG.s3Endpoint}/minio/health/live`).then(ok=>live.textContent=ok?"Reachable":"Blocked by browser/CORS"),probe(`${CONFIG.s3Endpoint}/minio/health/ready`).then(ok=>ready.textContent=ok?"Reachable":"Blocked by browser/CORS")])}
async function probe(url){try{await fetch(url,{method:"GET",mode:"no-cors",cache:"no-store"});return true}catch(_){return false}}
async function adminApi(path){const token=sessionStorage.getItem("minio_access_token")||localStorage.getItem("minio_access_token");if(!token)throw new Error("Missing admin token");const res=await fetch(`${CONFIG.adminApiBase}${path}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!res.ok)throw new Error(`Admin API failed: ${res.status}`);return res.json()}
function formatBytes(value){const units=["B","KB","MB","GB","TB"];let size=Number(value)||0;let unit=0;while(size>=1024&&unit<units.length-1){size/=1024;unit++}return `${size.toFixed(unit?1:0)} ${units[unit]}`}
function renderAdminObjects(objects){const table=$("[data-admin-objects-table]");if(!table)return;table.innerHTML=objects.length?objects.map(item=>`<tr><td>${escapeHtml(item.key)}</td><td>${formatBytes(item.size)}</td><td>${escapeHtml(item.contentType)}</td><td>${escapeHtml(item.lastModified)}</td></tr>`).join(""):`<tr><td colspan="4">No objects returned for the current prefix.</td></tr>`}
async function refreshAdminMetadata(){const status=$("[data-admin-api-status]");if(status)status.textContent="Loading protected metadata";try{const [summary,listing]=await Promise.all([adminApi("/summary"),adminApi("/objects?limit=25")]);const bucket=$("[data-admin-bucket]");if(bucket)bucket.textContent=summary.bucket;const count=$("[data-admin-object-count]");if(count)count.textContent=String(summary.objectCount);const bytes=$("[data-admin-total-bytes]");if(bytes)bytes.textContent=formatBytes(summary.totalBytes);const newest=$("[data-admin-newest]");if(newest) newest.textContent=summary.newestObjectModifiedAt||"No objects";renderAdminObjects(listing.objects||[]);if(status)status.textContent=summary.truncated?"Loaded partial protected metadata":"Loaded protected metadata"}catch(error){if(status)status.textContent="Protected metadata unavailable";console.warn(error)}}
async function bootAuthState(){saveTokensFromHash();const authUser=await validateAuth();if(authUser){const authState=$("[data-auth-state]");if(authState)authState.textContent="Signed in";const identity=$("[data-client-identity]");if(identity)identity.textContent=`Signed in as ${userLabel(authUser)}.`}const roles=normalizeRoles(authUser);const isAdmin=roles.some(role=>CONFIG.adminRoles.includes(role));if(isAdmin){const lock=$("[data-admin-lock]");const data=$("[data-admin-data]");if(lock&&data){lock.hidden=true;data.hidden=false;$("[data-admin-identity]").textContent=`Administrator session validated for ${userLabel(authUser)}.`;refreshAdminHealth();refreshAdminMetadata()}}}
function bind(){const menu=$("[data-menu-toggle]");if(menu)menu.addEventListener("click",()=>$(".nav").classList.toggle("open"));$$('[data-auth-register]').forEach(button=>button.addEventListener("click",()=>window.location.href=authUrl("register",button.dataset.authTarget)));$$('[data-auth-login]').forEach(button=>button.addEventListener("click",()=>window.location.href=authUrl("login",button.dataset.authTarget)));$("[data-lead-form]")?.addEventListener("submit",submitLead);$("[data-app-form]")?.addEventListener("submit",addApplication);$("[data-admin-refresh]")?.addEventListener("click",()=>{refreshAdminHealth();refreshAdminMetadata()})}
bind();renderApplications();bootAuthState();
