server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /admin { rewrite ^ /admin/ last; }
  location /admin/ { index index.html; try_files $uri $uri/ /admin/index.html; }
  location = /client { rewrite ^ /client/ last; }
  location /client/ { index index.html; try_files $uri $uri/ /client/index.html; }
  location / { try_files $uri $uri/ /index.html; }
}
